import path from 'path';

import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./tests/setup.ts'],
    css: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      exclude: [
        'node_modules/',
        'tests/',
        '**/*.d.ts',
        '**/*.config.*',
        '**/dist/**',
        '.vite/**',
        'guidelines/**',
        'public/**',
        'src/main.tsx',
        'src/app/App.tsx',
        'src/app/version.ts',
        'src/app/types/**',
        'src/app/components/ui/**',
        'src/app/components/services/multi-instance/**',
        'src/app/components/settings/**',
        'src/styles/**',
        'src/app/locales/**',
        'src/app/components/figma/**',
        'src/app/components/panels/**',
        'src/app/components/*-page.tsx',
        'src/app/components/*-page-temp.tsx',
        'src/app/components/*-context.tsx',
        'src/app/components/*-standalone.tsx',
        'src/app/components/cyberpunk-*.tsx',
        'src/app/components/insights-enhanced.tsx',
        'src/app/components/model-settings.tsx',
        'src/app/components/model-settings-types.ts',
        'src/app/components/provider-card.tsx',
        'src/app/components/theme-config.tsx',
        'src/app/components/theme-switcher-*.tsx',
        'src/app/components/particle-canvas.tsx',
        'src/app/components/page-transition.tsx',
        'src/app/components/pwa-install.tsx',
        'src/app/components/preload-fix.tsx',
        'src/app/components/onboarding-tutorial.tsx',
        'src/app/components/notification-drawer.tsx',
        'src/app/components/data-export-modal.tsx',
        'src/app/components/command-palette.tsx',
        'src/app/components/code-editor.tsx',
        'src/app/components/contact-book.tsx',
        'src/app/components/form-*.tsx',
        'src/app/components/number-database.tsx',
        'src/app/components/smart-form-system.tsx',
        'src/app/components/chat-interface.tsx',
        'src/app/components/yyc3-*.{ts,tsx}',
        'src/app/components/liquid-glass-wrapper.tsx',
        'src/app/components/neon-card.tsx',
        'src/app/components/cyber-tooltip.tsx',
        'src/app/components/cyberpunk-widget.tsx',
        'src/app/components/glitch-text.tsx',
        'src/app/components/module-placeholder-page.tsx',
        'src/app/components/activity-log.tsx',
        'src/app/components/diagnostics-panel.tsx',
        'src/app/components/module-configs.ts',
      ],
      thresholds: {
        lines: 80,
        branches: 80,
        functions: 80,
        statements: 80,
      },
    },
    include: ['tests/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['tests/e2e/**/*', 'node_modules/**/*'],
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
