import {
  createContext,
  type ReactNode,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
} from 'react';

// ==========================================
// YYC³ 全局状态管理 — Context API + localStorage
// Phase 4: + Realtime simulation, export utils, keyboard shortcuts
// ==========================================

/**
 * Unique identifier for each navigable page in the application.
 * Used by `AppContext` to track the currently active view.
 */
export type PageId =
  | 'dashboard'
  | 'chat'
  | 'clm'
  | 'aicall'
  | 'tools'
  | 'workflow'
  | 'insights'
  | 'settings'
  | 'logs'
  | 'forms'
  | 'contacts'
  | 'customerCare'
  | 'profile'
  | 'collab'
  // Platform Integration (平台集成)
  | 'paramSettings'
  | 'platformSettings'
  | 'wechatConfig'
  | 'channelCenter'
  | 'dataIntegration'
  // HR & Finance (人资财务)
  | 'compensation'
  | 'finance'
  // Supply Chain (供应链)
  | 'procurement'
  | 'inventory'
  // AI Marketing (智能营销)
  | 'marketingPlan'
  | 'promotionExec'
  | 'marketingAnalytics'
  | 'marketingAssets'
  | 'customerAcquisition'
  | 'brandMgmt'
  | 'intelligentOps'
  | 'platformHub'
  | 'aiCreativeTools'
  | 'aiMarketingEngine'
  | 'appOverview'
  | 'aiDecisionSupport'
  | 'nlpProcessing'
  // Quick Actions (一键操作)
  | 'quickActions'
  // Task Board (任务看板)
  | 'taskBoard'
  // Developer Workspace (开发工作台)
  | 'devWorkspace';

/**
 * Application display mode.
 * - `standalone`: Full-screen desktop layout with sidebar navigation.
 * - `widget`: Compact floating panel mode for embedding.
 */
export type AppMode = 'standalone' | 'widget';

/**
 * Visual theme configuration controlling cyberpunk effects intensity.
 * Each boolean toggle enables/disables a specific visual layer;
 * `neonIntensity` (0-100) scales the glow strength of all neon elements.
 */
export interface ThemeConfig {
  neonIntensity: number; // 0-100
  scanlineEnabled: boolean;
  glitchEnabled: boolean;
  circuitGridEnabled: boolean;
  dataFlowEnabled: boolean;
  springAnimEnabled: boolean;
  blurEnabled: boolean;
}

const defaultTheme: ThemeConfig = {
  neonIntensity: 80,
  scanlineEnabled: true,
  glitchEnabled: true,
  circuitGridEnabled: true,
  dataFlowEnabled: true,
  springAnimEnabled: true,
  blurEnabled: true,
};

interface AppState {
  activePage: PageId;
  appMode: AppMode;
  sidebarPinned: boolean;
  notifications: NotificationItem[];
  recentActivities: ActivityItem[];
  theme: ThemeConfig;
  onboardingDone: boolean;
  mobileSidebarOpen: boolean;
}

/**
 * A single notification entry displayed in the notification drawer.
 * Notifications are generated by the realtime simulation or user actions.
 */
export interface NotificationItem {
  id: string;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  color: string;
  timestamp: Date;
  read: boolean;
}

/**
 * A single activity record shown in the activity feed and log page.
 * Activities are auto-generated by the realtime simulation system.
 */
export interface ActivityItem {
  id: string;
  action: string;
  target: string;
  timestamp: Date;
  type: 'customer' | 'call' | 'system' | 'ai';
  color: string;
}

interface AppContextType extends AppState {
  setActivePage: (page: PageId) => void;
  setAppMode: (mode: AppMode) => void;
  setSidebarPinned: (pinned: boolean) => void;
  addNotification: (n: Omit<NotificationItem, 'id' | 'timestamp' | 'read'>) => void;
  markNotificationRead: (id: string) => void;
  clearNotifications: () => void;
  addActivity: (a: Omit<ActivityItem, 'id' | 'timestamp'>) => void;
  unreadCount: number;
  updateTheme: (partial: Partial<ThemeConfig>) => void;
  resetTheme: () => void;
  setOnboardingDone: (done: boolean) => void;
  setMobileSidebarOpen: (open: boolean) => void;
  neonAlpha: (base: number) => number; // helper: scales alpha by neonIntensity
}

const STORAGE_KEY = 'yyc3_app_state';
const THEME_STORAGE_KEY = 'yyc3_theme';
const ONBOARDING_KEY = 'yyc3_onboarding_done';

// Serializable subset for localStorage
interface PersistedState {
  activePage: PageId;
  appMode: AppMode;
  sidebarPinned: boolean;
}

function loadPersistedState(): Partial<PersistedState> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      return {
        activePage: parsed.activePage || 'dashboard',
        appMode: parsed.appMode || 'standalone',
        sidebarPinned: parsed.sidebarPinned ?? false,
      };
    }
  } catch {
    // ignore parse errors
  }
  return {};
}

function savePersistedState(state: PersistedState) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // ignore storage errors
  }
}

function loadTheme(): ThemeConfig {
  try {
    const raw = localStorage.getItem(THEME_STORAGE_KEY);
    if (raw) return { ...defaultTheme, ...JSON.parse(raw) };
  } catch {
    /* ignore */
  }
  return { ...defaultTheme };
}

function saveTheme(theme: ThemeConfig) {
  try {
    localStorage.setItem(THEME_STORAGE_KEY, JSON.stringify(theme));
  } catch {
    /* ignore */
  }
}

function loadOnboardingDone(): boolean {
  try {
    return localStorage.getItem(ONBOARDING_KEY) === 'true';
  } catch {
    return false;
  }
}

// Mock initial notifications
const initialNotifications: NotificationItem[] = [
  {
    id: 'n1',
    title: '新客户转化',
    message: '张明远已从「获客」阶段进入「转化」阶段，AI 评估转化概率 87%',
    type: 'success',
    color: '#00ffc8',
    timestamp: new Date(Date.now() - 300000),
    read: false,
  },
  {
    id: 'n2',
    title: 'AI 呼叫完成',
    message: '批量外呼任务 #247 已完成，接通率 78.3%，转化 12 条有效线索',
    type: 'info',
    color: '#00f0ff',
    timestamp: new Date(Date.now() - 1200000),
    read: false,
  },
  {
    id: 'n3',
    title: '客户健康度预警',
    message: '王建华（量子计算）健康度降至 65，建议尽快安排跟进',
    type: 'warning',
    color: '#00d4ff',
    timestamp: new Date(Date.now() - 2400000),
    read: false,
  },
  {
    id: 'n4',
    title: 'AI 话术更新',
    message: '产品推荐话术 v3.2 已自动生成并部署，覆盖 3 个场景',
    type: 'info',
    color: '#00f0ff',
    timestamp: new Date(Date.now() - 3600000),
    read: false,
  },
  {
    id: 'n5',
    title: '系统性能优化',
    message: '缓存策略已自动调整，API 响应时间优化 18%',
    type: 'success',
    color: '#00ffc8',
    timestamp: new Date(Date.now() - 5400000),
    read: true,
  },
  {
    id: 'n6',
    title: '内存使用警告',
    message: '内存使用已达 67%，建议优化缓存策略或扩容',
    type: 'warning',
    color: '#00d4ff',
    timestamp: new Date(Date.now() - 7200000),
    read: true,
  },
  {
    id: 'n7',
    title: '赵鹏飞续约成功',
    message: '未来能源年度合同已续签，合同金额 ¥1,024,000',
    type: 'success',
    color: '#00ffc8',
    timestamp: new Date(Date.now() - 10800000),
    read: true,
  },
];

// Mock initial activities
const initialActivities: ActivityItem[] = [
  {
    id: 'a1',
    action: 'AI 自动跟进',
    target: '陈雅文 · 智链网络',
    timestamp: new Date(Date.now() - 120000),
    type: 'ai',
    color: '#00d4ff',
  },
  {
    id: 'a2',
    action: '呼叫完成',
    target: '赵鹏飞 · 未来能源 (3:45)',
    timestamp: new Date(Date.now() - 600000),
    type: 'call',
    color: '#00ffcc',
  },
  {
    id: 'a3',
    action: '客户健康度更新',
    target: '李思琪 健康度 88 → 92',
    timestamp: new Date(Date.now() - 1800000),
    type: 'customer',
    color: '#00f0ff',
  },
  {
    id: 'a4',
    action: '系统性能优化',
    target: '缓存策略已自动调整',
    timestamp: new Date(Date.now() - 3600000),
    type: 'system',
    color: '#00ffc8',
  },
  {
    id: 'a5',
    action: '新客户录入',
    target: '王建华 · 量子计算 ¥64,000',
    timestamp: new Date(Date.now() - 5400000),
    type: 'customer',
    color: '#00d4ff',
  },
  {
    id: 'a6',
    action: 'AI 话术生成',
    target: '产品推荐话术 v3.2 已就绪',
    timestamp: new Date(Date.now() - 7200000),
    type: 'ai',
    color: '#00f0ff',
  },
];

const AppContext = createContext<AppContextType | null>(null);

/**
 * Root application state provider.
 * Manages page navigation, notifications, activities, theme config,
 * onboarding status, and mobile sidebar state.
 * Persists serializable subset to `localStorage`.
 */
export function AppProvider({ children }: { children: ReactNode }) {
  const persisted = loadPersistedState();

  const [activePage, setActivePageRaw] = useState<PageId>(persisted.activePage || 'dashboard');
  const [appMode, setAppModeRaw] = useState<AppMode>(persisted.appMode || 'standalone');
  const [sidebarPinned, setSidebarPinnedRaw] = useState(persisted.sidebarPinned ?? false);
  const [notifications, setNotifications] = useState<NotificationItem[]>(initialNotifications);
  const [recentActivities, setRecentActivities] = useState<ActivityItem[]>(initialActivities);
  const [theme, setTheme] = useState<ThemeConfig>(loadTheme);
  const [onboardingDone, setOnboardingDoneRaw] = useState(loadOnboardingDone);
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false);

  // Persist state changes
  useEffect(() => {
    savePersistedState({ activePage, appMode, sidebarPinned });
  }, [activePage, appMode, sidebarPinned]);

  // Persist theme changes
  useEffect(() => {
    saveTheme(theme);
  }, [theme]);

  const setActivePage = useCallback((page: PageId) => {
    setActivePageRaw(page);
  }, []);

  const setAppMode = useCallback((mode: AppMode) => {
    setAppModeRaw(mode);
  }, []);

  const setSidebarPinned = useCallback((pinned: boolean) => {
    setSidebarPinnedRaw(pinned);
  }, []);

  const addNotification = useCallback((n: Omit<NotificationItem, 'id' | 'timestamp' | 'read'>) => {
    setNotifications(prev =>
      [
        {
          ...n,
          id: `n_${Date.now()}`,
          timestamp: new Date(),
          read: false,
        },
        ...prev,
      ].slice(0, 50),
    );
  }, []);

  const markNotificationRead = useCallback((id: string) => {
    setNotifications(prev => prev.map(n => (n.id === id ? { ...n, read: true } : n)));
  }, []);

  const clearNotifications = useCallback(() => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  }, []);

  const addActivity = useCallback((a: Omit<ActivityItem, 'id' | 'timestamp'>) => {
    setRecentActivities(prev =>
      [
        {
          ...a,
          id: `a_${Date.now()}`,
          timestamp: new Date(),
        },
        ...prev,
      ].slice(0, 20),
    );
  }, []);

  const updateTheme = useCallback((partial: Partial<ThemeConfig>) => {
    setTheme(prev => ({ ...prev, ...partial }));
  }, []);

  const resetTheme = useCallback(() => {
    setTheme({ ...defaultTheme });
  }, []);

  const setOnboardingDone = useCallback((done: boolean) => {
    setOnboardingDoneRaw(done);
    try {
      localStorage.setItem(ONBOARDING_KEY, String(done));
    } catch {
      /* ignore */
    }
  }, []);

  const neonAlpha = useCallback(
    (base: number) => {
      return base * (theme.neonIntensity / 100);
    },
    [theme.neonIntensity],
  );

  const unreadCount = notifications.filter(n => !n.read).length;

  return (
    <AppContext.Provider
      value={{
        activePage,
        appMode,
        sidebarPinned,
        notifications,
        recentActivities,
        theme,
        onboardingDone,
        mobileSidebarOpen,
        setActivePage,
        setAppMode,
        setSidebarPinned,
        addNotification,
        markNotificationRead,
        clearNotifications,
        addActivity,
        unreadCount,
        updateTheme,
        resetTheme,
        setOnboardingDone,
        setMobileSidebarOpen,
        neonAlpha,
      }}
    >
      {children}
    </AppContext.Provider>
  );
}

/**
 * Hook to access the global application state and dispatch actions.
 * Must be called within an `<AppProvider>` tree.
 *
 * @throws Error if called outside of `AppProvider`.
 */
export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}

// ==========================================
// Realtime Simulation Hook — Phase 4
// Simulates WebSocket-like data pushes
// ==========================================

const realtimeNotifPool: Array<Omit<NotificationItem, 'id' | 'timestamp' | 'read'>> = [
  {
    title: '新线索转入',
    message: '刘晓东（芯片科技）已进入获客阶段，来源：官网表单',
    type: 'info',
    color: '#00f0ff',
  },
  {
    title: 'AI 呼叫接通',
    message: '当前通话：周婷 · 银河传媒，情感分析：积极',
    type: 'success',
    color: '#00ffc8',
  },
  {
    title: '客户流失风险',
    message: '孙磊（深海科技）健康度降至 52，触发预警',
    type: 'warning',
    color: '#00d4ff',
  },
  {
    title: '批量任务完成',
    message: '外呼任务 #251 结束：42通完成，接通率 81.2%',
    type: 'success',
    color: '#00ffc8',
  },
  {
    title: 'AI 学习更新',
    message: '情感模型 v4.3 训练完成，准确率提升 2.1%',
    type: 'info',
    color: '#00f0ff',
  },
  {
    title: '安全扫描完成',
    message: '0 威胁检测，系统安全等级 A+',
    type: 'success',
    color: '#00ffc8',
  },
  {
    title: '呼叫异常检测',
    message: '连续 3 通未接通，建议检查线路或调整时段',
    type: 'error',
    color: '#005f73',
  },
  {
    title: '客户升级',
    message: '陈雅文（智链网络）忠诚度评分升至 A+ 级',
    type: 'success',
    color: '#00ffc8',
  },
];

const realtimeActivityPool: Array<Omit<ActivityItem, 'id' | 'timestamp'>> = [
  { action: 'AI 自动外呼', target: '刘晓东 · 芯片科技', type: 'call', color: '#00ffcc' },
  { action: '客户画像更新', target: '周婷 · 银河传媒 标签+3', type: 'customer', color: '#00f0ff' },
  { action: '话术优化推送', target: '场景：续约挽回 v2.1', type: 'ai', color: '#00d4ff' },
  { action: '系统负载均衡', target: '节点 3 流量已分流 15%', type: 'system', color: '#00ffc8' },
  { action: 'AI 情感分析', target: '当前通话情绪：中性→积极', type: 'ai', color: '#00d4ff' },
  { action: '新客户录入', target: '马浩然 · 极光数据 ¥88,000', type: 'customer', color: '#00f0ff' },
  { action: '呼叫完成', target: '周婷 · 银河传媒 (5:21)', type: 'call', color: '#00ffcc' },
  { action: '缓存清理', target: '释放 128MB · 内存使用率 -4%', type: 'system', color: '#00ffc8' },
];

/**
 * Simulates WebSocket-like realtime data pushes.
 * Periodically injects notifications (every 15-25 s) and activities
 * (every 8-15 s) from a rotating pool of mock data.
 */
export function useRealtimeSimulation() {
  const { addNotification, addActivity } = useApp();
  const notifIdxRef = useRef(0);
  const actIdxRef = useRef(0);

  useEffect(() => {
    // Push a random notification every 15-25s
    const notifTimer = setInterval(
      () => {
        const item = realtimeNotifPool[notifIdxRef.current % realtimeNotifPool.length];
        addNotification(item);
        notifIdxRef.current++;
      },
      15000 + Math.random() * 10000,
    );

    // Push a random activity every 8-15s
    const actTimer = setInterval(
      () => {
        const item = realtimeActivityPool[actIdxRef.current % realtimeActivityPool.length];
        addActivity(item);
        actIdxRef.current++;
      },
      8000 + Math.random() * 7000,
    );

    return () => {
      clearInterval(notifTimer);
      clearInterval(actTimer);
    };
  }, [addNotification, addActivity]);
}

// ==========================================
// KPI Realtime Fluctuation Hook — Phase 4
// Returns slightly fluctuating metric values
// ==========================================

/**
 * Live KPI data structure returned by {@link useLiveKPI}.
 * Values fluctuate slightly every 5 seconds to simulate realtime updates.
 */
export interface LiveKPI {
  customers: number;
  calls: number;
  aiTasks: number;
  responseMs: number;
  refreshKey: number; // increments on each update for animation trigger
}

/**
 * Hook returning slightly fluctuating KPI metrics, updating every 5 s.
 * Useful for dashboard live counters and sparkline animations.
 */
export function useLiveKPI(): LiveKPI {
  const [kpi, setKpi] = useState<LiveKPI>({
    customers: 1388,
    calls: 247,
    aiTasks: 1892,
    responseMs: 12,
    refreshKey: 0,
  });

  useEffect(() => {
    const timer = setInterval(() => {
      setKpi(prev => ({
        customers: prev.customers + Math.floor(Math.random() * 3) - (Math.random() > 0.7 ? 1 : 0),
        calls: prev.calls + Math.floor(Math.random() * 4),
        aiTasks: prev.aiTasks + Math.floor(Math.random() * 8) + 1,
        responseMs: Math.max(8, Math.min(18, prev.responseMs + (Math.random() > 0.5 ? 1 : -1))),
        refreshKey: prev.refreshKey + 1,
      }));
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  return kpi;
}

// ==========================================
// Export Data Utilities — Phase 4
// ==========================================

/**
 * Metadata describing a dataset available for CSV/JSON export.
 * Used by the `DataExportModal` to render selection UI.
 */
export interface ExportableDataset {
  id: string;
  label: string;
  description: string;
  color: string;
  rowCount: number;
  fields: string[];
  getData: () => Record<string, any>[];
}

const mockCustomerExport = () => [
  {
    姓名: '张明远',
    公司: '星际科技',
    阶段: '转化',
    价值: '¥128,000',
    健康度: 92,
    最近联系: '2小时前',
  },
  {
    姓名: '李思琪',
    公司: '云端数据',
    阶段: '成交',
    价值: '¥256,000',
    健康度: 88,
    最近联系: '1天前',
  },
  {
    姓名: '王建华',
    公司: '量子计算',
    阶段: '获客',
    价值: '¥64,000',
    健康度: 65,
    最近联系: '3天前',
  },
  {
    姓名: '陈雅文',
    公司: '智链网络',
    阶段: '服务',
    价值: '¥512,000',
    健康度: 95,
    最近联系: '刚刚',
  },
  {
    姓名: '赵鹏飞',
    公司: '未来能源',
    阶段: '忠诚',
    价值: '¥1,024,000',
    健康度: 98,
    最近联系: '5小时前',
  },
  { 姓名: '刘晓东', 公司: '芯片科技', 阶段: '获客', 价值: '¥42,000', 健康度: 70, 最近联系: '刚刚' },
  {
    姓名: '周婷',
    公司: '银河传媒',
    阶段: '转化',
    价值: '¥186,000',
    健康度: 82,
    最近联系: '30分钟前',
  },
  {
    姓名: '马浩然',
    公司: '极光数据',
    阶段: '获客',
    价值: '¥88,000',
    健康度: 75,
    最近联系: '1小时前',
  },
];

// Mock Dashboard Export Data (Weekly Metrics)
const mockDashboardExport = () => [
  { 日期: '周一', 新客户: 42, 呼叫数: 35, AI任务: 128, 转化率: '38.2%' },
  { 日期: '周二', 新客户: 56, 呼叫数: 48, AI任务: 156, 转化率: '41.5%' },
  { 日期: '周三', 新客户: 38, 呼叫数: 32, AI任务: 112, 转化率: '35.8%' },
  { 日期: '周四', 新客户: 67, 呼叫数: 58, AI任务: 189, 转化率: '44.2%' },
  { 日期: '周五', 新客户: 72, 呼叫数: 64, AI任务: 201, 转化率: '47.1%' },
  { 日期: '周六', 新客户: 45, 呼叫数: 28, AI任务: 95, 转化率: '33.9%' },
  { 日期: '周日', 新客户: 52, 呼叫数: 42, AI任务: 167, 转化率: '40.6%' },
];

const mockCallExport = () => [
  { 姓名: '张明远', 公司: '星际科技', 类型: 'AI外呼', 状态: '已完成', 时长: '2:34', AI评分: 92 },
  { 姓名: '李思琪', 公司: '云端数据', 类型: 'AI跟进', 状态: '等待中', 时长: '--', AI评分: 85 },
  { 姓名: '王建华', 公司: '量子计算', 类型: '人工转接', 状态: '排队中', 时长: '--', AI评分: 67 },
  { 姓名: '陈雅文', 公司: '智链网络', 类型: 'AI回访', 状态: '已完成', 时长: '6:12', AI评分: 96 },
  { 姓名: '赵鹏飞', 公司: '未来能源', 类型: 'AI外呼', 状态: '已完成', 时长: '3:45', AI评分: 88 },
];

/** Pre-configured exportable datasets covering dashboard, customer, and call data. */
export const exportableDatasets: ExportableDataset[] = [
  {
    id: 'dashboard',
    label: '数据驾驶舱',
    description: '7日运营趋势、KPI汇总数据',
    color: '#00f0ff',
    rowCount: 7,
    fields: ['日期', '新客户', '呼叫数', 'AI任务', '转化率'],
    getData: mockDashboardExport,
  },
  {
    id: 'customers',
    label: '客户数据',
    description: '全量客户信息、生命周期阶段、健康度',
    color: '#00d4ff',
    rowCount: 8,
    fields: ['姓名', '公司', '阶段', '价值', '健康度', '最近联系'],
    getData: mockCustomerExport,
  },
  {
    id: 'calls',
    label: '呼叫记录',
    description: 'AI呼叫队列、通话时长、AI评分',
    color: '#00ffcc',
    rowCount: 5,
    fields: ['姓名', '公司', '类型', '状态', '时长', 'AI评分'],
    getData: mockCallExport,
  },
];

/**
 * Exports an array of records as a UTF-8 BOM CSV file download.
 *
 * @param data - Array of flat key-value objects to serialize.
 * @param filename - Download filename without extension (`.csv` is appended).
 */
export function exportToCSV(data: Record<string, any>[], filename: string): void {
  if (!data.length) return;
  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(','),
    ...data.map(row =>
      headers
        .map(h => {
          const val = String(row[h] ?? '');
          return val.includes(',') || val.includes('"') ? `"${val.replace(/"/g, '""')}"` : val;
        })
        .join(','),
    ),
  ];
  const blob = new Blob([`\uFEFF${csvRows.join('\n')}`], { type: 'text/csv;charset=utf-8' });
  downloadBlob(blob, `${filename}.csv`);
}

/**
 * Exports an array of records as a pretty-printed JSON file download.
 *
 * @param data - Array of objects to serialize.
 * @param filename - Download filename without extension (`.json` is appended).
 */
export function exportToJSON(data: Record<string, any>[], filename: string): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  downloadBlob(blob, `${filename}.json`);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
